apiVersion: apps/v1
kind: Deployment
metadata:
  name: pos-txn-monitor-dotnet
spec:
  selector:
    matchLabels:
      app: pos-txn-monitor-dotnet
  template:
    metadata:
      labels:
        app: pos-txn-monitor-dotnet
    spec:
      containers:
      - name: pos-txn-monitor-dotnet
        image: harbor.eqix.vmwedge.com/apps/pos-txn-monitor-dotnet-wrightmi@sha256:6b1db6a20b336cf5d982c25fa81ec15b6fb363134361ee62398ffb639cd9659b
        ports:
        - name: http
          containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: pos-txn-monitor-dotnet
  labels:
    app: pos-txn-monitor-dotnet
spec:
  ports:
  - port: 80
    targetPort: http
  selector:
    app: pos-txn-monitor-dotnet

