apiVersion: apps/v1
kind: Deployment
metadata:
  name: pos-txn-monitor-dotnet
  annotations:
    kapp.k14s.io/update-strategy: fallback-on-replace
    ootb.apps.tanzu.vmware.com/servicebinding-workload: "true"
  labels:
    app.kubernetes.io/part-of: tanzu-edge-pos
    apps.tanzu.vmware.com/has-tests: "true"
    apps.tanzu.vmware.com/workload-type: server
    app.kubernetes.io/component: run
    carto.run/workload-name: pos-txn-monitor-dotnet
spec:
  selector:
    matchLabels:
      app.kubernetes.io/component: run
      app.kubernetes.io/part-of: tanzu-edge-pos
      apps.tanzu.vmware.com/has-tests: "true"
      apps.tanzu.vmware.com/workload-type: server
      carto.run/workload-name: pos-txn-monitor-dotnet
  template:
    metadata:
      annotations:
        conventions.carto.run/applied-conventions: appliveview-sample/app-live-view-appflavour-check
        developer.conventions/target-containers: workload
      labels:
        app.kubernetes.io/component: run
        app.kubernetes.io/part-of: tanzu-edge-pos
        apps.tanzu.vmware.com/has-tests: "true"
        apps.tanzu.vmware.com/workload-type: server
        carto.run/workload-name: pos-txn-monitor-dotnet
    spec:
      containers:
      - env:
        - name: RabbitMQ__Host
          valueFrom:
            secretKeyRef:
              key: host
              name: edge-pos-messaging-default-user
              optional: false
        - name: RabbitMQ__StreamPort
          valueFrom:
            secretKeyRef:
              key: stream-port
              name: edge-pos-messaging-default-user
              optional: false
        - name: RabbitMQ__Username
          valueFrom:
            secretKeyRef:
              key: username
              name: edge-pos-messaging-default-user
              optional: false
        - name: RabbitMQ__Password
          valueFrom:
            secretKeyRef:
              key: password
              name: edge-pos-messaging-rabbitmq
              optional: false
        - name: POSTxnMonitor__StoreId
          valueFrom:
            configMapKeyRef:
              key: POSTxnMonitor__StoreId
              name: store-config
        image: harbor.eqix.vmwedge.com/apps/pos-txn-monitor-dotnet-wrightmi@sha256:a9d4fb8d30c46a01480f704aa11daca36bb061d64c3ccf3ba49059eba64138dd
        name: workload
        resources: {}
        securityContext:
          runAsUser: 1000
      serviceAccountName: default
---
apiVersion: v1
kind: Service
metadata:
  name: pos-txn-monitor-dotnet
  labels:
    app.kubernetes.io/part-of: tanzu-edge-pos
    apps.tanzu.vmware.com/has-tests: "true"
    apps.tanzu.vmware.com/workload-type: server
    app.kubernetes.io/component: run
    carto.run/workload-name: pos-txn-monitor-dotnet
spec:
  selector:
    app.kubernetes.io/component: run
    app.kubernetes.io/part-of: tanzu-edge-pos
    apps.tanzu.vmware.com/has-tests: "true"
    apps.tanzu.vmware.com/workload-type: server
    carto.run/workload-name: pos-txn-monitor-dotnet
  ports:
  - targetPort: 8080
    port: 8080
    name: http

